language: python

python: "3.6"

before_install:
 # install radiance
 - wget https://github.com/NREL/Radiance/releases/download/5.2.1/radiance-5.2.91bcc23df3-Linux.tar.gz
 - tar -xzvf radiance-5.2.91bcc23df3-Linux.tar.gz
 - sudo cp -a radiance-5.2.91bcc23df3-Linux/usr/local/radiance/bin/. /usr/local/bin
 - sudo cp -a radiance-5.2.91bcc23df3-Linux/usr/local/radiance/lib/. /usr/local/lib/ray
 - sudo apt-get install libtiff5

install:
 - pip install pytest pytest-cov coveralls
 - pip install lbt-ladybug

script:
  - py.test --cov=. ./tests/

after_success:
  - coverage report
  - coveralls


jobs:
  include:
    - stage: deploy
      if: branch = master AND (NOT type IN (pull_request))
      python: "3.6"
      env: TRAVIS=true
      script:
        - git config --global user.name "ladybugbot"
        - git config --global user.email "release@ladybug.tools"
        - pip install python-semantic-release
        - semantic-release publish
